import Head from 'next/head'
import { Footer } from 'src/components/Footer'
import { Header } from 'src/components/Header'
import Main from 'src/components/Main'
import { useBgLightBlue } from 'src/hooks/useBgLightBlue'
import { useCounter } from 'src/hooks/useCounter'
import { useInputArray } from 'src/hooks/useInputArray'
import styles from '../styles/Home.module.css'

export default function About() {
  const {count, isShow, handleClick, handleDisplay} = useCounter();
  const {text, array, handleChange, handleAdd} = useInputArray();
  useBgLightBlue();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      {isShow ? <h1>{count}</h1> : null}
      <button onClick= {handleDisplay}>
        {isShow ? "非表示" : "表示"}
      </button>
      <button onClick = {handleClick}>ボタン</button>
      <input type="text" value={text} onChange={handleChange}/>

      <button onClick = {handleAdd}>追加</button>
      <ul>
        {array.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul>

      <Main page="about"/>

      <Footer />
    </div>
  )
}
