import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Footer } from 'src/components/Footer'
import { Header } from 'src/components/Header'
import Main from 'src/components/Main'
import styles from '../styles/Home.module.css'

// const handleClick = (e) => {
//   console.log(e.target.href);
//   e.preventDefault();
// }

export default function Home() {
  const [count, setCount] = useState(1);

  const handleClick = (e) => {
    setCount(count => count + 1);
    setCount(count => count + 1);
  };

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <h1>{count}</h1>
      <button
       onClick = {handleClick}
       >
        ボタン
      </button>

      <Main page="index"/>

      <Footer />

    </div>
  )
}
