import Head from 'next/head'
import { Comments as CommentsComponent } from 'src/components/Comments'
import { Header } from 'src/components/Header'

const Comments = () => {
  return (
    <div>
      <Head>
        <title>Comments</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <CommentsComponent />

    </div>
  )
}

export default Comments;